# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Master_pb2 as Master__pb2


class MapWorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MapWorker = channel.unary_unary(
                '/Master.MapWorkerService/MapWorker',
                request_serializer=Master__pb2.FileLocations.SerializeToString,
                response_deserializer=Master__pb2.FileLocations.FromString,
                )


class MapWorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MapWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MapWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.MapWorker,
                    request_deserializer=Master__pb2.FileLocations.FromString,
                    response_serializer=Master__pb2.FileLocations.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Master.MapWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MapWorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MapWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master.MapWorkerService/MapWorker',
            Master__pb2.FileLocations.SerializeToString,
            Master__pb2.FileLocations.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ReduceWorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReduceWorker = channel.unary_unary(
                '/Master.ReduceWorkerService/ReduceWorker',
                request_serializer=Master__pb2.FileLocations.SerializeToString,
                response_deserializer=Master__pb2.FileLocations.FromString,
                )


class ReduceWorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReduceWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReduceWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReduceWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.ReduceWorker,
                    request_deserializer=Master__pb2.FileLocations.FromString,
                    response_serializer=Master__pb2.FileLocations.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Master.ReduceWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReduceWorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReduceWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Master.ReduceWorkerService/ReduceWorker',
            Master__pb2.FileLocations.SerializeToString,
            Master__pb2.FileLocations.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
