# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Master.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cMaster.proto\x12\x06Master\"%\n\rFileLocations\x12\x14\n\x0c\x66ileLocation\x18\x01 \x03(\t2M\n\x10MapWorkerService\x12\x39\n\tMapWorker\x12\x15.Master.FileLocations\x1a\x15.Master.FileLocations2S\n\x13ReduceWorkerService\x12<\n\x0cReduceWorker\x12\x15.Master.FileLocations\x1a\x15.Master.FileLocationsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Master_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILELOCATIONS._serialized_start=24
  _FILELOCATIONS._serialized_end=61
  _MAPWORKERSERVICE._serialized_start=63
  _MAPWORKERSERVICE._serialized_end=140
  _REDUCEWORKERSERVICE._serialized_start=142
  _REDUCEWORKERSERVICE._serialized_end=225
# @@protoc_insertion_point(module_scope)
