# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cServer.proto\x12\x06Server\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1d\n\x08\x43lientId\x12\x11\n\tclient_id\x18\x01 \x01(\t\".\n\tCLIENTELE\x12!\n\x07\x63lients\x18\x01 \x03(\x0b\x32\x10.Server.ClientId\"\"\n\x0eServerResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x90\x01\n\x08\x41rticles\x12)\n\x0ftype_of_article\x18\x01 \x01(\x0e\x32\x10.Server.Category\x12\x13\n\x0b\x61uthor_name\x18\x02 \x01(\t\x12\x33\n\x0ftime_of_publish\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"6\n\x10\x41rticle_Response\x12\"\n\x08\x61rticles\x18\x01 \x03(\x0b\x32\x10.Server.Articles\"\xab\x01\n\x0f\x41rticle_Request\x12)\n\x0ftype_of_article\x18\x01 \x01(\x0e\x32\x10.Server.Category\x12\x13\n\x0b\x61uthor_name\x18\x02 \x01(\t\x12\x33\n\x0ftime_of_publish\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12#\n\tclient_id\x18\x04 \x01(\x0b\x32\x10.Server.ClientId\"5\n\x0c\x41ll_Articles\x12%\n\x0b\x61rticleList\x18\x01 \x03(\x0b\x32\x10.Server.Articles\"_\n\x15PublishArticleRequest\x12!\n\x07\x61rticle\x18\x01 \x01(\x0b\x32\x10.Server.Articles\x12#\n\tclient_id\x18\x02 \x01(\x0b\x32\x10.Server.ClientId*>\n\x08\x43\x61tegory\x12\x0b\n\x07NO_TYPE\x10\x00\x12\n\n\x06SPORTS\x10\x01\x12\x0b\n\x07\x46\x41SHION\x10\x02\x12\x0c\n\x08POLITICS\x10\x03\x32K\n\x11JoinServerService\x12\x36\n\nJoinServer\x12\x10.Server.ClientId\x1a\x16.Server.ServerResponse2M\n\x12LeaveServerService\x12\x37\n\x0bLeaveServer\x12\x10.Server.ClientId\x1a\x16.Server.ServerResponse2V\n\x12GetArticlesService\x12@\n\x0bGetArticles\x12\x17.Server.Article_Request\x1a\x18.Server.Article_Response2`\n\x15PublishArticleService\x12G\n\x0ePublishArticle\x12\x1d.Server.PublishArticleRequest\x1a\x16.Server.ServerResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CATEGORY._serialized_start=701
  _CATEGORY._serialized_end=763
  _CLIENTID._serialized_start=57
  _CLIENTID._serialized_end=86
  _CLIENTELE._serialized_start=88
  _CLIENTELE._serialized_end=134
  _SERVERRESPONSE._serialized_start=136
  _SERVERRESPONSE._serialized_end=170
  _ARTICLES._serialized_start=173
  _ARTICLES._serialized_end=317
  _ARTICLE_RESPONSE._serialized_start=319
  _ARTICLE_RESPONSE._serialized_end=373
  _ARTICLE_REQUEST._serialized_start=376
  _ARTICLE_REQUEST._serialized_end=547
  _ALL_ARTICLES._serialized_start=549
  _ALL_ARTICLES._serialized_end=602
  _PUBLISHARTICLEREQUEST._serialized_start=604
  _PUBLISHARTICLEREQUEST._serialized_end=699
  _JOINSERVERSERVICE._serialized_start=765
  _JOINSERVERSERVICE._serialized_end=840
  _LEAVESERVERSERVICE._serialized_start=842
  _LEAVESERVERSERVICE._serialized_end=919
  _GETARTICLESSERVICE._serialized_start=921
  _GETARTICLESSERVICE._serialized_end=1007
  _PUBLISHARTICLESERVICE._serialized_start=1009
  _PUBLISHARTICLESERVICE._serialized_end=1105
# @@protoc_insertion_point(module_scope)
