# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cServer.proto\x12\x06Server\"9\n\x04\x46ile\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"\'\n\x08\x46ileList\x12\x1b\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x0c.Server.File\"A\n\x12\x43lientWriteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\"F\n\x13\x43lientWriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"!\n\x11\x43lientReadRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"V\n\x12\x43lientReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"#\n\x13\x43lientDeleteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"&\n\x14\x43lientDeleteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\\\n\x12\x43lientWriteService\x12\x46\n\x0b\x43lientWrite\x12\x1a.Server.ClientWriteRequest\x1a\x1b.Server.ClientWriteResponse2X\n\x11\x43lientReadService\x12\x43\n\nClientRead\x12\x19.Server.ClientReadRequest\x1a\x1a.Server.ClientReadResponse2`\n\x13\x43lientDeleteService\x12I\n\x0c\x43lientDelete\x12\x1b.Server.ClientDeleteRequest\x1a\x1c.Server.ClientDeleteResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILE._serialized_start=24
  _FILE._serialized_end=81
  _FILELIST._serialized_start=83
  _FILELIST._serialized_end=122
  _CLIENTWRITEREQUEST._serialized_start=124
  _CLIENTWRITEREQUEST._serialized_end=189
  _CLIENTWRITERESPONSE._serialized_start=191
  _CLIENTWRITERESPONSE._serialized_end=261
  _CLIENTREADREQUEST._serialized_start=263
  _CLIENTREADREQUEST._serialized_end=296
  _CLIENTREADRESPONSE._serialized_start=298
  _CLIENTREADRESPONSE._serialized_end=384
  _CLIENTDELETEREQUEST._serialized_start=386
  _CLIENTDELETEREQUEST._serialized_end=421
  _CLIENTDELETERESPONSE._serialized_start=423
  _CLIENTDELETERESPONSE._serialized_end=461
  _CLIENTWRITESERVICE._serialized_start=463
  _CLIENTWRITESERVICE._serialized_end=555
  _CLIENTREADSERVICE._serialized_start=557
  _CLIENTREADSERVICE._serialized_end=645
  _CLIENTDELETESERVICE._serialized_start=647
  _CLIENTDELETESERVICE._serialized_end=743
# @@protoc_insertion_point(module_scope)
